version: '3.4'

# Please refer https://docs.docker.com/compose to learn more about Docker Compose.

# This is a sample docker-compose file with two services
# 1. yourwebapp is an sample web service where the docker container image will be built from the Dockerfile as
#    part of starting the compose.
# 2. redis is an existing image hosted in docker hub.
version: '3.4'

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:443
    networks:
      - lab-network
    depends_on: 
      - redis

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - lab-network
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "testes"
      RABBITMQ_DEFAULT_PASS: "RabbitMQ2019!"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lab-network

  sender:
    image: sender
    build:
      context: ../Send/
      dockerfile: Dockerfile
    networks:
      - lab-network
    depends_on: 
      - rabbitmq
      - webapi

  receiver:
    image: receiver
    build:
      context: ../Receive/
      dockerfile: Dockerfile
    networks:
      - lab-network
    depends_on: 
      - redis
      - rabbitmq

networks: 
  lab-network:
      driver: bridge
# docker-compose -f docker-compose.yml up -d --build
